import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className='bg-background'>
      <body>
        <main className="min-h-screen flex flex-col items-center container m-auto relative">
          {children}
        </main>
      </body>
    </html>
  )
}
